[testenv]
extras =
    test
    zstd
commands = pytest {posargs:-m "not no_extra"}

[testenv:full]

[testenv:min]
extras = test
commands = pytest {posargs:-m "not extra"}

[testenv:cov]
extras = test
         zstd
commands = pytest --cov virt_backup --cov-config .coveragerc {posargs:-m "not no_extra"}

[testenv:black]
deps = black
skip_install = true
commands = black --check virt_backup tests
